version: "3.7"

services:
  app:
    image: papereira/devcontainer-elixir:alpine
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - elixir-artifacts:/home/vscode/elixir-artifacts
    environment:
      - TZ=Europe/Lisbon
      - ELIXIR_BUILD_PATH=/home/vscode/elixir-artifacts/_build
      - ELIXIR_DEPS_PATH=/home/vscode/elixir-artifacts/deps
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
    ports:
      - 4000:4000
    networks:
      - default
      - infra

volumes:
  elixir-artifacts: {}

networks:
  infra:
    external:
      name: infra_network
